// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';
import { readFileSync } from 'node:fs';
import siteKit from '@shaharia-lab/site-kit';
import agentoCode from '@shaharia-lab/site-kit/themes/agento-code';
import { SITE, BASE, REPO, SITE_REPO, OG_IMAGE, SITE_NAME, abs, url, gtmId, gtmSnippet, consentDefaultSnippet, consentBannerSnippet } from './site.config.mjs';
import { GROUPS, PAGES } from './docs.manifest.mjs';

/**
 * The half of the <head> that Starlight owns.
 *
 * Starlight builds its own head and does not read src/layouts/Page.astro, so
 * anything that must be true of EVERY page has to be stated twice: once in
 * that layout, once here. Only what Starlight does not already emit belongs in
 * this list. It emits the title, description, canonical, `og:title`,
 * `og:description`, `og:url`, `og:type`, `og:locale`, `og:site_name` and
 * `twitter:card` itself, and repeating one of those produces a duplicate tag
 * rather than an override.
 *
 * What it does not emit is an image, which is why a share of a docs page would
 * otherwise render a blank card.
 */
/** @type {NonNullable<Parameters<typeof starlight>[0]['head']>} */
const starlightHead = [
  { tag: 'meta', attrs: { property: 'og:image', content: abs(OG_IMAGE.path) } },
  { tag: 'meta', attrs: { property: 'og:image:width', content: String(OG_IMAGE.width) } },
  { tag: 'meta', attrs: { property: 'og:image:height', content: String(OG_IMAGE.height) } },
  {
    tag: 'meta',
    attrs: {
      property: 'og:image:alt',
      content: OG_IMAGE.alt,
    },
  },
  { tag: 'meta', attrs: { name: 'twitter:image', content: abs(OG_IMAGE.path) } },
];

// Analytics, on the same terms as the other half: absent entirely when no
// container id was supplied to the build. See gtmId() in site.config.mjs.
// Consent Mode's defaults have to reach the dataLayer before the container
// does, so these push in order: default, container, banner. Starlight has no
// body extension point, which is why the banner is a script rather than
// markup. See consentBannerSnippet() in site.config.mjs.
const gtm = gtmId();
if (gtm) {
  starlightHead.push(
    { tag: 'script', content: consentDefaultSnippet() },
    { tag: 'script', content: gtmSnippet(gtm) },
    {
      tag: 'script',
      content: consentBannerSnippet(url('/docs/user-guide/self-hosting/')),
    },
  );
}

/**
 * The sidebar is derived from the manifest, so it cannot drift from the pages.
 *
 * Starlight's slug for a generated file is its path under src/content/docs
 * without the extension, and sync-docs.mjs writes `<slug>.md` under `docs/`.
 * So the manifest's `slug` maps straight through, with `index` collapsing to
 * the section root the same way it does in the routes.
 */
/** @param {{ slug: string }} p */
const slugOf = (p) => (p.slug === 'index' ? 'docs' : `docs/${p.slug}`);

const sidebar = [
  ...PAGES.filter((p) => p.group === null).map((p) => ({ label: p.label, slug: slugOf(p) })),
  ...GROUPS.map((g) => ({
    label: g.label,
    collapsed: g.collapsed ?? false,
    items: PAGES.filter((p) => p.group === g.id).map((p) => ({ label: p.label, slug: slugOf(p) })),
  })),
];

/**
 * Edit on GitHub, per page. The pages under src/content/docs are generated by
 * sync-docs.mjs from docs/, and that generated copy is gitignored, so the link
 * has to name the file in docs/ that a contributor should actually edit. The
 * manifest already knows both halves: the entry id Starlight sees (slugOf) and
 * the source file. A page missing from this map gets no edit link at all.
 */
const editSources = Object.fromEntries(PAGES.map((p) => [slugOf(p), `docs/${p.file}`]));

/**
 * The star count for the Star button in the docs header. fetch-release.mjs
 * writes it before every dev and build run (`npm run sync`); when that could
 * not reach GitHub, or has not run, the button shows without a count.
 */
function repoStars() {
  try {
    const repo = JSON.parse(readFileSync(new URL('./src/data/repo.json', import.meta.url), 'utf8'));
    return repo.resolved ? repo.stars : null;
  } catch {
    return null;
  }
}

export default defineConfig({
  site: SITE,
  // A GitHub Pages project site, so every route carries the repository name.
  // See site.config.mjs for why BASE is written without a trailing slash.
  base: BASE || '/',
  trailingSlash: 'always',
  integrations: [
    starlight({
      title: SITE_NAME,
      // The theme (fonts, design tokens, Starlight surfaces, code blocks) comes
      // from site-kit's agento-code theme; only the site's own additions are
      // listed here.
      customCss: ['./src/styles/consent.css'],
      description:
        'The open-source knowledge base your AI tools read from and write back to: prompts, rules, memory and artifacts, shared over MCP. Self-hosted.',
      head: starlightHead,
      social: [{ icon: 'github', label: 'GitHub', href: REPO }],
      // site-kit adds the page actions under every docs title (Copy page, Open
      // in ChatGPT / Claude, View as Markdown, Edit on GitHub), a Markdown twin
      // of every page at its URL plus `.md`, llms.txt, and the Star button.
      plugins: siteKit({
        theme: agentoCode({ accent: 'ink' }),
        repo: { url: REPO, stars: repoStars() },
        // Docs live in this repository, not the product's, so edits go here.
        editLink: { baseUrl: `${SITE_REPO}/edit/main/`, sources: editSources },
        // Starlight's footer plus the cookie-settings link. See the file for
        // why the docs half needs its own.
        components: { Footer: './src/components/starlight/Footer.astro' },
      }),
      sidebar,
      // The docs pages are generated from docs/ by scripts/sync-docs.mjs.
      // Editing them in src/content/ has no effect; the next build overwrites.
      // The 404 is a site page (src/pages/404.astro), not a docs page: landing
      // on the docs sidebar reads as "this documentation page is missing"
      // rather than "this address is wrong".
      disable404Route: true,
      lastUpdated: false,
      pagination: true,
      credits: false,
    }),
    sitemap(),
  ],
});
