/**
 * Renders design/og-image.html to public/og.png at 1200×630.
 *
 * The output is COMMITTED, unlike everything else generated under web/. That is
 * deliberate: this needs a Chrome binary, and the Pages build runs on a runner
 * where installing one to redraw a file that changes about once a year would be
 * minutes of every deploy. So the PNG is an asset in the repository and this
 * script is how it is regenerated by hand:
 *
 *     npm run build:og
 *
 * It is not wired into `npm run build`, and check-links.mjs skips .png, so
 * nothing in CI depends on Chrome being present.
 */
import { spawn } from 'node:child_process';
import { access, rename, rm } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, '../design/og-image.html');
const OUT = resolve(here, '../public/og.png');

/** The image is meta-tagged at this size, so the two must not drift. */
const WIDTH = 1200;
const HEIGHT = 630;

const CANDIDATES = [
  process.env.CHROME_PATH,
  'google-chrome',
  'google-chrome-stable',
  'chromium',
  'chromium-browser',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
].filter(Boolean);

function run(bin, args) {
  return new Promise((ok, fail) => {
    const child = spawn(bin, args, { stdio: ['ignore', 'ignore', 'pipe'] });
    let err = '';
    child.stderr.on('data', (b) => (err += b));
    child.on('error', fail);
    child.on('close', (code) => (code === 0 ? ok() : fail(new Error(err.trim() || `exit ${code}`))));
  });
}

async function main() {
  // Chrome writes the screenshot into the working directory under a fixed name
  // when --screenshot is given no path on some builds, so it is given one and
  // then moved: that way a partial write never replaces a good committed PNG.
  const tmp = `${OUT}.tmp.png`;
  await rm(tmp, { force: true });

  const args = [
    '--headless',
    '--disable-gpu',
    '--hide-scrollbars',
    // The card's two @font-face rules read the brand faces out of
    // node_modules by relative path. A file:// page is not allowed to fetch a
    // file:// subresource without this, and the failure is silent: the card
    // renders in a fallback serif and mono, which looks almost right and is
    // not the brand.
    '--allow-file-access-from-files',
    '--force-device-scale-factor=1',
    `--window-size=${WIDTH},${HEIGHT}`,
    `--screenshot=${tmp}`,
    `file://${SRC}`,
  ];

  let lastError;
  for (const bin of CANDIDATES) {
    try {
      await run(bin, args);
      await access(tmp);
      await rename(tmp, OUT);
      console.log(`render-og: ${OUT.split('/').slice(-2).join('/')} at ${WIDTH}×${HEIGHT} via ${bin}`);
      return;
    } catch (err) {
      lastError = err;
    }
  }

  await rm(tmp, { force: true });
  console.error(
    `render-og: no usable Chrome found (tried ${CANDIDATES.join(', ')}).\n` +
      `Set CHROME_PATH to one. Last error: ${lastError?.message ?? 'none'}`,
  );
  process.exit(1);
}

await main();
